# Generated by Django 2.2.3 on 2019-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_shelter', '0003_auto_20191126_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_shelter.Dog'),
        ),
    ]
