# Generated by Django 2.2.3 on 2019-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_shelter', '0004_auto_20191126_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
