# Generated by Django 2.2.3 on 2019-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
