# Generated by Django 2.2.3 on 2019-11-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelter', '0002_dog_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog', to='dog_shelter.Dog'),
        ),
    ]
